<?php

namespace Database\Seeders;


// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Allergie;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {


        //Vult de allergies tabel met data

        DB::table('allergies')->insert([
            [
                'id' => 1,
                'allergie_naam' => 'Gluten',
                'allergie_omschrijving' => 'Allergisch voor gluten',
                'Anafylactisch_risico' => 'zeerlaag',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
            [
                'id' => 2,
                'allergie_naam' => 'Pindas',
                'allergie_omschrijving' => 'Allergisch voor pindas',
                'Anafylactisch_risico' => 'Hoog',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
            [
                'id' => 3,
                'allergie_naam' => 'Schaaldieren',
                'allergie_omschrijving' => 'Allergisch voor schaaldieren',
                'Anafylactisch_risico' => 'RedelijkHoog',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
            [
                'id' => 4,
                'allergie_naam' => 'Hazelnoten',
                'allergie_omschrijving' => 'Allergisch voor hazelnoten',
                'Anafylactisch_risico' => 'laag',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
            [
                'id' => 5,
                'allergie_naam' => 'Lactose',
                'allergie_omschrijving' => 'Allergisch voor lactose',
                'Anafylactisch_risico' => 'Zeerlaag',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
            [
                'id' => 6,
                'allergie_naam' => 'Soja',
                'allergie_omschrijving' => 'Allergisch voor soja',
                'Anafylactisch_risico' => 'Zeerlaag',
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:09',
                'datum_gewijzigd' => '2023-06-21 10:46:09',
            ],
        ]);
        //vult de persoon tabel met data

        DB::table('persoon')->insert([
            [
                'id' => 1,
                'gezin_id' => NULL,
                'voornaam' => 'Hans',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Leeuwen',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'manager',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 2,
                'gezin_id' => NULL,
                'voornaam' => 'Jan',
                'tussenvoegsel' => 'van der',
                'achternaam' => 'Sluijs',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'medewerker',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 3,
                'gezin_id' => NULL,
                'voornaam' => 'Herman',
                'tussenvoegsel' => 'den',
                'achternaam' => 'Duiker',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'vrijwilliger',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 4,
                'gezin_id' => 1,
                'voornaam' => 'Johan',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 6,
                'gezin_id' => 1,
                'voornaam' => 'Theo',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 7,
                'gezin_id' => 1,
                'voornaam' => 'Jantien',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 8,
                'gezin_id' => 2,
                'voornaam' => 'Arjan',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 9,
                'gezin_id' => 2,
                'voornaam' => 'Janneke',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Sanders',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 10,
                'gezin_id' => 2,
                'voornaam' => 'Stein',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 11,
                'gezin_id' => 2,
                'voornaam' => 'Judith',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 12,
                'gezin_id' => 3,
                'voornaam' => 'Mazin',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Vliet',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 13,
                'gezin_id' => 3,
                'voornaam' => 'Selma',
                'tussenvoegsel' => 'van de',
                'achternaam' => 'Heuvel',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 14,
                'gezin_id' => 4,
                'voornaam' => 'Eva',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Scherder',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 15,
                'gezin_id' => 4,
                'voornaam' => 'Tim',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Scherder',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55',
            ],
            [
                'id' => 16,
                'gezin_id' => 4,
                'voornaam' => 'Devin',
                'tussenvoegsel' => NULL,
                'achternaam' => 'Scherder',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55'
            ],
            [
                'id' => 17,
                'gezin_id' => 5,
                'voornaam' => 'Frieda',
                'tussenvoegsel' => 'de',
                'achternaam' => 'Jong',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55'
            ],
            [
                'id' => 18,
                'gezin_id' => 5,
                'voornaam' => 'Simeon',
                'tussenvoegsel' => 'de',
                'achternaam' => 'Jong',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 0,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55'
            ],
            [
                'id' => 19,
                'gezin_id' => 6,
                'voornaam' => 'Hanna',
                'tussenvoegsel' => 'van der',
                'achternaam' => 'Berg',
                'geboortedatum' => '0000-00-00',
                'typepersoon' => 'klant',
                'IsVertegenwoordiger' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:46:55',
                'datum_gewijzigd' => '2023-06-21 10:46:55'
            ],
        ]);

        //vult de allergie_per_persoon tabel met data

        DB::table('allergie_per_persoon')->insert([
            [
                'id' => 1,
                'allergies_id' => 1,
                'persoon_id' => 4,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 2,
                'allergies_id' => 2,
                'persoon_id' => 5,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 3,
                'allergies_id' => 3,
                'persoon_id' => 6,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 4,
                'allergies_id' => 4,
                'persoon_id' => 7,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 5,
                'allergies_id' => 3,
                'persoon_id' => 8,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 6,
                'allergies_id' => 2,
                'persoon_id' => 9,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 7,
                'allergies_id' => 5,
                'persoon_id' => 10,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 8,
                'allergies_id' => 2,
                'persoon_id' => 12,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 9,
                'allergies_id' => 4,
                'persoon_id' => 13,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 10,
                'allergies_id' => 1,
                'persoon_id' => 14,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 11,
                'allergies_id' => 3,
                'persoon_id' => 15,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 12,
                'allergies_id' => 5,
                'persoon_id' => 16,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ],
            [
                'id' => 13,
                'allergies_id' => 1,
                'persoon_id' => 17,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:47:46',
                'datum_gewijzigd' => '2023-06-21 10:47:46'
            ]
        ]);

        //vult de gezin tabel met data

        DB::table('gezin')->insert([
            [
                'id' => 1,
                'gezin_naam' => 'ZevenhuizenGezin',
                'code' => 'G0001',
                'gezin_omschrijving' => 'Bijstandsgezin',
                'aantal_volwassenen' => 2,
                'aantal_kinderen' => 2,
                'aantal_babys' => 0,
                'totaal_aantal_personen' => 4,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
            [
                'id' => 2,
                'gezin_naam' => 'BergkampGezin',
                'code' => 'G0002',
                'gezin_omschrijving' => 'Bijstandsgezin',
                'aantal_volwassenen' => 2,
                'aantal_kinderen' => 1,
                'aantal_babys' => 1,
                'totaal_aantal_personen' => 4,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
            [
                'id' => 3,
                'gezin_naam' => 'HeuvelGezin',
                'code' => 'G0003',
                'gezin_omschrijving' => 'Bijstandsgezin',
                'aantal_volwassenen' => 2,
                'aantal_kinderen' => 0,
                'aantal_babys' => 0,
                'totaal_aantal_personen' => 2,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
            [
                'id' => 4,
                'gezin_naam' => 'ScherderGezin',
                'code' => 'G0004',
                'gezin_omschrijving' => 'Bijstandsgezin',
                'aantal_volwassenen' => 1,
                'aantal_kinderen' => 0,
                'aantal_babys' => 2,
                'totaal_aantal_personen' => 3,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
            [
                'id' => 5,
                'gezin_naam' => 'DeJongGezin',
                'code' => 'G0005',
                'gezin_omschrijving' => 'Bijstandsgezin',
                'aantal_volwassenen' => 1,
                'aantal_kinderen' => 1,
                'aantal_babys' => 0,
                'totaal_aantal_personen' => 2,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
            [
                'id' => 6,
                'gezin_naam' => 'VanderBergGezin',
                'code' => 'G0006',
                'gezin_omschrijving' => 'AlleenGaande',
                'aantal_volwassenen' => 1,
                'aantal_kinderen' => 0,
                'aantal_babys' => 0,
                'totaal_aantal_personen' => 1,
                'IsActief' => 1,
                'Opmerking' => NULL,
                'datum_aangemaakt' => '2023-06-21 10:45:41',
                'datum_gewijzigd' => '2023-06-21 10:45:41'
            ],
        ]);
    }
}
